### ISSUE TITLE
race condition bugs in make_image_products

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/distributed-pipeline#24]
The following probably happens when this process is reading the fits file (this happens to the the end_after_day2) while the other process is writing to it. The solution is to first have all the image products go to scratch and then copy the diferenced images and the snapshot images back to lustre.
```
  | Traceback (most recent call last):   File "/opt/astro/devel/yuping/distributed-pipeline/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task     R = retval = fun(*args, **kwargs)   File "/opt/astro/devel/yuping/distributed-pipeline/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__     return self.run(*args, **kwargs)   File "/opt/astro/devel/yuping/distributed-pipeline/.venv/lib/python3.6/site-packages/celery/app/base.py", line 490, in run     return task._orig_run(*args, **kwargs)   File "/opt/astro/devel/yuping/distributed-pipeline/orca/proj/transientbatchtasks.py", line 118, in make_image_products     image_sub.image_sub(snapshots2[i], snapshots2[i+1], outdir2)   File "/opt/astro/devel/yuping/distributed-pipeline/orca/utils/image_sub.py", line 17, in image_sub     hdulist2 = fits.open(file2)   File "/opt/astro/devel/yuping/distributed-pipeline/.venv/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 165, in fitsopen     lazy_load_hdus, **kwargs)   File "/opt/astro/devel/yuping/distributed-pipeline/.venv/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 405, in fromfile     lazy_load_hdus=lazy_load_hdus, **kwargs)   File "/opt/astro/devel/yuping/distributed-pipeline/.venv/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1088, in _readfrom     raise OSError('Empty or corrupt FITS file') OSError: Empty or corrupt FITS file
-- | --
```

For this next one. The measurement set is the first in a chunk (which means that it's also the after_end measurement set for someone else).

the following comes from the fact that I got my arguments backward in `gainscaling.py`...scaled the wrong measurement set.
```
Traceback (most recent call last):
  File "/opt/astro/devel/yuping/distributed-pipeline/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/astro/devel/yuping/distributed-pipeline/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/astro/devel/yuping/distributed-pipeline/.venv/lib/python3.6/site-packages/celery/app/base.py", line 490, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/astro/devel/yuping/distributed-pipeline/orca/proj/transientbatchtasks.py", line 83, in make_image_products
    gainscale_target_parents=ms_parent_day2_list + [ms_parent_after_end_day2])
  File "/opt/astro/devel/yuping/distributed-pipeline/orca/proj/transientbatchtasks.py", line 211, in _parallel_copy_chgcentre_gainscale
    for s in spw_list
  File "/opt/astro/devel/yuping/distributed-pipeline/.venv/lib/python3.6/site-packages/billiard/pool.py", line 1399, in starmap
    starmapstar, chunksize).get()
  File "/opt/astro/devel/yuping/distributed-pipeline/.venv/lib/python3.6/site-packages/billiard/pool.py", line 1791, in get
    raise self._value.exception
RuntimeError: Error (Resource deadlock avoided) when acquiring lock on /lustre/yuping/0-100-hr-reduction/final/msfiles/2018-03-23/hh=15/2018-03-23T15:46:26/08_2018-03-23T15:46:26.ms/table.lock
```

**Comment by yupinghuang** [comment]
Fixed by
https://github.com/ovro-lwa/distributed-pipeline/commit/fb84960c4e9c529bb4b3d4ec7cc4e5444be907a8
https://github.com/ovro-lwa/distributed-pipeline/commit/95c4f1123565843350d8237b412140f67c793721
